### ISSUE TITLE
Add checker for python code

### ISSUE THREAD

**Issue by nashif** [zephyrproject-rtos/ci-tools#20] opened 2019-02-23 02:17 UTC
Check for python syntax using one of the many linters:
- flake8
- pylint
- ..

preferably this should work on diffs rather on complete files.

**Comment by marc-hb** [comment] 2019-03-19 17:08
BTW here's `pylint`'s most missing feature, especially in the context of focusing on new code and ignoring warnings on existing code:
```shell
usefulpylint() { pylint "$@" | sort -t ":" -k 2,2n ; }
usefulpylint -E scripts/sanitycheck
```

**Comment by ulfalizer** [comment] 2019-03-19 22:11
Only takes ~5 seconds or so run `pylint3` on all `.py` files in the tree, so for stuff that should always generate a failure, it's easy to do that instead.

**Comment by marc-hb** [comment] 2019-03-20 17:43
Duplicate of issue https://github.com/zephyrproject-rtos/zephyr/issues/10338 ?

**Closed** 2019-09-13 15:52 UTC
Labels: enhancement
